-- ============ enums ============
CREATE TYPE public.app_role AS ENUM ('admin', 'project_manager', 'developer');
CREATE TYPE public.task_status AS ENUM ('todo', 'in_progress', 'in_review', 'done');
CREATE TYPE public.task_priority AS ENUM ('low', 'medium', 'high', 'critical');

-- ============ profiles ============
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  full_name text NOT NULL,
  email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ============ user_roles ============
CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_user_roles_user_id ON public.user_roles (user_id);

-- ============ role helpers (security definer, avoid RLS recursion) ============
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role);
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin');
$$;

CREATE OR REPLACE FUNCTION public.is_manager()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role IN ('admin','project_manager'));
$$;

-- ============ clients ============
CREATE TABLE public.clients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_email text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.clients TO authenticated;
GRANT ALL ON public.clients TO service_role;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

-- ============ projects ============
CREATE TABLE public.projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid REFERENCES public.clients(id) ON DELETE SET NULL,
  name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'active',
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO authenticated;
GRANT ALL ON public.projects TO service_role;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_projects_created_by ON public.projects (created_by);
CREATE INDEX idx_projects_client_id ON public.projects (client_id);

-- ============ tasks ============
CREATE TABLE public.tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_number integer GENERATED BY DEFAULT AS IDENTITY,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  assignee_id uuid,
  status public.task_status NOT NULL DEFAULT 'todo',
  priority public.task_priority NOT NULL DEFAULT 'medium',
  due_date timestamptz,
  is_overdue boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tasks TO authenticated;
GRANT ALL ON public.tasks TO service_role;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX idx_tasks_task_number ON public.tasks (task_number);
CREATE INDEX idx_tasks_project_id ON public.tasks (project_id);
CREATE INDEX idx_tasks_assignee_id ON public.tasks (assignee_id);
CREATE INDEX idx_tasks_status ON public.tasks (status);
CREATE INDEX idx_tasks_priority ON public.tasks (priority);
CREATE INDEX idx_tasks_due_date ON public.tasks (due_date);
CREATE INDEX idx_tasks_assignee_status ON public.tasks (assignee_id, status);

-- ============ task_activity ============
CREATE TABLE public.task_activity (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid REFERENCES public.tasks(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  actor_id uuid,
  action text NOT NULL,
  from_status public.task_status,
  to_status public.task_status,
  detail text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.task_activity TO authenticated;
GRANT ALL ON public.task_activity TO service_role;
ALTER TABLE public.task_activity ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_activity_project_created ON public.task_activity (project_id, created_at DESC);
CREATE INDEX idx_activity_task_id ON public.task_activity (task_id);
CREATE INDEX idx_activity_created_at ON public.task_activity (created_at DESC);

-- ============ notifications ============
CREATE TABLE public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL,
  type text NOT NULL,
  task_id uuid REFERENCES public.tasks(id) ON DELETE CASCADE,
  project_id uuid REFERENCES public.projects(id) ON DELETE CASCADE,
  message text NOT NULL,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, UPDATE ON public.notifications TO authenticated;
GRANT ALL ON public.notifications TO service_role;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_notifications_recipient_read ON public.notifications (recipient_id, read_at);
CREATE INDEX idx_notifications_recipient_created ON public.notifications (recipient_id, created_at DESC);

-- ============ visibility helpers ============
CREATE OR REPLACE FUNCTION public.can_view_project(_project_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.is_admin()
    OR EXISTS (SELECT 1 FROM public.projects p WHERE p.id = _project_id AND p.created_by = auth.uid())
    OR EXISTS (SELECT 1 FROM public.tasks t WHERE t.project_id = _project_id AND t.assignee_id = auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.can_manage_project(_project_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.is_admin()
    OR EXISTS (SELECT 1 FROM public.projects p WHERE p.id = _project_id AND p.created_by = auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.can_view_task(_task_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.tasks t
    WHERE t.id = _task_id
      AND (t.assignee_id = auth.uid() OR public.can_manage_project(t.project_id))
  );
$$;

-- ============ policies ============
CREATE POLICY "profiles readable by signed-in team" ON public.profiles
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert own profile" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "update own profile" ON public.profiles
  FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());

CREATE POLICY "roles readable by signed-in team" ON public.user_roles
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "clients visible to managers" ON public.clients
  FOR SELECT TO authenticated USING (public.is_manager());
CREATE POLICY "admins insert clients" ON public.clients
  FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "admins update clients" ON public.clients
  FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "admins delete clients" ON public.clients
  FOR DELETE TO authenticated USING (public.is_admin());

CREATE POLICY "projects visible to owner admin or assignee" ON public.projects
  FOR SELECT TO authenticated USING (public.can_view_project(id));
CREATE POLICY "managers create own projects" ON public.projects
  FOR INSERT TO authenticated WITH CHECK (public.is_manager() AND created_by = auth.uid());
CREATE POLICY "owners update projects" ON public.projects
  FOR UPDATE TO authenticated USING (public.can_manage_project(id)) WITH CHECK (public.can_manage_project(id));
CREATE POLICY "owners delete projects" ON public.projects
  FOR DELETE TO authenticated USING (public.can_manage_project(id));

CREATE POLICY "tasks visible to assignee or project manager" ON public.tasks
  FOR SELECT TO authenticated USING (assignee_id = auth.uid() OR public.can_manage_project(project_id));
CREATE POLICY "project owners create tasks" ON public.tasks
  FOR INSERT TO authenticated WITH CHECK (public.can_manage_project(project_id));
CREATE POLICY "owners or assignee update tasks" ON public.tasks
  FOR UPDATE TO authenticated
  USING (public.can_manage_project(project_id) OR assignee_id = auth.uid())
  WITH CHECK (public.can_manage_project(project_id) OR assignee_id = auth.uid());
CREATE POLICY "owners delete tasks" ON public.tasks
  FOR DELETE TO authenticated USING (public.can_manage_project(project_id));

CREATE POLICY "activity visible by task or project scope" ON public.task_activity
  FOR SELECT TO authenticated
  USING (public.can_manage_project(project_id) OR (task_id IS NOT NULL AND public.can_view_task(task_id)));
CREATE POLICY "activity insert by actor" ON public.task_activity
  FOR INSERT TO authenticated WITH CHECK (actor_id = auth.uid());

CREATE POLICY "own notifications" ON public.notifications
  FOR SELECT TO authenticated USING (recipient_id = auth.uid());
CREATE POLICY "update own notifications" ON public.notifications
  FOR UPDATE TO authenticated USING (recipient_id = auth.uid()) WITH CHECK (recipient_id = auth.uid());

-- ============ column-level guard: developers may only move status ============
CREATE OR REPLACE FUNCTION public.guard_task_update()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  NEW.updated_at := now();
  IF auth.uid() IS NOT NULL AND NOT public.can_manage_project(NEW.project_id) THEN
    IF NEW.title <> OLD.title
       OR COALESCE(NEW.description,'') <> COALESCE(OLD.description,'')
       OR COALESCE(NEW.assignee_id, '00000000-0000-0000-0000-000000000000') <> COALESCE(OLD.assignee_id, '00000000-0000-0000-0000-000000000000')
       OR NEW.priority <> OLD.priority
       OR COALESCE(NEW.due_date, 'epoch'::timestamptz) <> COALESCE(OLD.due_date, 'epoch'::timestamptz)
       OR NEW.project_id <> OLD.project_id THEN
      RAISE EXCEPTION 'Developers may only change task status';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_guard_task_update BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.guard_task_update();

-- ============ activity + notification triggers ============
CREATE OR REPLACE FUNCTION public.log_task_insert()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE actor uuid := COALESCE(auth.uid(), NEW.created_by);
BEGIN
  INSERT INTO public.task_activity (task_id, project_id, actor_id, action, to_status, detail)
  VALUES (NEW.id, NEW.project_id, actor, 'created', NEW.status, NEW.title);

  IF NEW.assignee_id IS NOT NULL THEN
    INSERT INTO public.task_activity (task_id, project_id, actor_id, action, detail)
    VALUES (NEW.id, NEW.project_id, actor, 'assigned', NEW.title);
    INSERT INTO public.notifications (recipient_id, type, task_id, project_id, message)
    VALUES (NEW.assignee_id, 'task_assigned', NEW.id, NEW.project_id,
            'You were assigned Task #' || NEW.task_number || ': ' || NEW.title);
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_log_task_insert AFTER INSERT ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.log_task_insert();

CREATE OR REPLACE FUNCTION public.log_task_update()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  actor uuid := auth.uid();
  pm uuid;
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.task_activity (task_id, project_id, actor_id, action, from_status, to_status, detail)
    VALUES (NEW.id, NEW.project_id, actor, 'status_changed', OLD.status, NEW.status, NEW.title);

    IF NEW.status = 'in_review' THEN
      SELECT created_by INTO pm FROM public.projects WHERE id = NEW.project_id;
      IF pm IS NOT NULL AND pm IS DISTINCT FROM actor THEN
        INSERT INTO public.notifications (recipient_id, type, task_id, project_id, message)
        VALUES (pm, 'task_in_review', NEW.id, NEW.project_id,
                'Task #' || NEW.task_number || ' is ready for review: ' || NEW.title);
      END IF;
    END IF;
  END IF;

  IF NEW.assignee_id IS DISTINCT FROM OLD.assignee_id AND NEW.assignee_id IS NOT NULL THEN
    INSERT INTO public.task_activity (task_id, project_id, actor_id, action, detail)
    VALUES (NEW.id, NEW.project_id, actor, 'assigned', NEW.title);
    INSERT INTO public.notifications (recipient_id, type, task_id, project_id, message)
    VALUES (NEW.assignee_id, 'task_assigned', NEW.id, NEW.project_id,
            'You were assigned Task #' || NEW.task_number || ': ' || NEW.title);
  END IF;

  IF NEW.is_overdue AND NOT OLD.is_overdue THEN
    INSERT INTO public.task_activity (task_id, project_id, actor_id, action, detail)
    VALUES (NEW.id, NEW.project_id, NULL, 'flagged_overdue', NEW.title);
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_log_task_update AFTER UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.log_task_update();

-- ============ overdue sweeper (scheduled) ============
CREATE OR REPLACE FUNCTION public.flag_overdue_tasks()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE flagged integer;
BEGIN
  WITH upd AS (
    UPDATE public.tasks
    SET is_overdue = true
    WHERE is_overdue = false
      AND status <> 'done'
      AND due_date IS NOT NULL
      AND due_date < now()
    RETURNING 1
  ) SELECT count(*) INTO flagged FROM upd;

  UPDATE public.tasks SET is_overdue = false
  WHERE is_overdue = true AND (status = 'done' OR due_date IS NULL OR due_date >= now());

  RETURN flagged;
END;
$$;
REVOKE ALL ON FUNCTION public.flag_overdue_tasks() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.flag_overdue_tasks() TO service_role;

-- ============ realtime ============
ALTER TABLE public.tasks REPLICA IDENTITY FULL;
ALTER TABLE public.task_activity REPLICA IDENTITY FULL;
ALTER TABLE public.notifications REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.task_activity;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;